### ISSUE TITLE
Downgrade Go Version to 1.20

### ISSUE THREAD

**Issue by gustavosbarreto** [xakep666/mongo-migrate#25]
I have observed that the current minimum required Go version specified in the latest release necessitates an unnecessary upgrade to Go 1.22. Through testing on my own fork, I have verified that Go 1.20 is sufficient for compatibility. Please consider downgrading the minimum required Go version from 1.22 to 1.20.

Setting the lowest possible Go version is a good practice for publicly available Go packages. By doing so, you avoid imposing specific Go version requirements on all consumers of your package.

**Comment by xakep666** [comment]
Merged. Thanks!
